baseURL = "https://scgmlz.github.io/MIEZEPY_website/"
theme = "hugo-theme-scgdoc"
languageCode = "en-us"
title = "MIEZEPY"
MetaDataFormat = "toml"
canonifyURLs = true
sectionPagesMenu = "main"

paginate = 5

# Code
PygmentsCodeFences = true
PygmentsUseClassic = false
PygmentsUseClasses = true
PygmentsStyle = "vs"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "MIEZEPY Documentation"
  Author = "Alexander Schober"
  email = "alex.schober@mac.com"
  custom_css = ["css/MIEZEPY.css"]
  custom_js = ["js/MIEZEPY.js"]
  logo = "img/site-logo.png"
  Debug = false

[[params.social]]
    title = "github"
    url = "https://github.com/scgmlz/NSE_Soft"

[params.authors.author1]
  name = "Alexander Schober"
  url = "http://first-author.com"
  
[params.authors.author2]
  name = "Gennady Pospelov"
  url = "http://second-author.com"

[[menu.main]]
  name = "Home"
  identifier="home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "News"
  identifier="post"
  url = "/post/"
  weight = 30

[[menu.main]]
  name = "Documentation"
  identifier = "documentation"
  url = "/documentation/"
  weight = 40

